package com.vanhack.forum;

public enum UserTestType {
	FIND_BY_NICKNAME,
	FIND_BY_EMAIL,
	USER_OK,
	EMPTY_NICKNAME,
	EMPTY_EMAIL,
	EMPTY_PASSWORD,
	SHORTER_NICKNAME,
	SHORTER_PASSWORD,
	LONGER_NICKNAME,
	INVALID_EMAIL;
}
